---
apiVersion: v1
kind: Namespace
metadata:
  name: omegaverse
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: omega
  name: omega
  namespace: omegaverse
spec:
  containers:
  - name: omega
    args:
    - /bin/tail
    - -f
    - /dev/null
    image: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: omega
  name: omegay
  namespace: omegaverse
spec:
  containers:
  - name: omegay
    args:
    - /bin/tail
    - -f
    - /dev/null
    image: busybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
